# Generated by Django 4.0.5 on 2022-10-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=800)),
                ('materia', models.CharField(max_length=100)),
                ('arquivo', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
