# Generated by Django 4.0.3 on 2022-10-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcodec', '0002_alter_repositorio_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='codigo',
            field=models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False),
        ),
    ]
