# Generated by Django 4.0.3 on 2022-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcodec', '0004_alter_repositorio_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
