# Generated by Django 4.0.3 on 2022-10-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcodec', '0005_alter_repositorio_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=800)),
                ('materia', models.CharField(max_length=100)),
                ('arquivo', models.FileField(blank=True, upload_to='tcc/pdf')),
            ],
        ),
    ]
