# Generated by Django 4.0.5 on 2022-11-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcodec', '0008_rename_materia_tcc_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='descricao',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='descricao',
            field=models.CharField(max_length=999),
        ),
    ]
